### ISSUE TITLE
Need to return the gradients from optimizer

### ISSUE THREAD

**Issue by daoducanhc** [apache/singa#1081]
Need to return the gradients from the optimizer for calculating the training-free metric

**Comment by daoducanhc** [comment]
the gradients are returned in the line 242 of https://github.com/apache/singa/commit/d9831d917ae0918749faacf5a611b161cbdd1fc9#diff-882c3945309d2e5184aa4c29cbbcc2eb0c95911af8319b5332d049ba72f55aecR242

**Comment by zmeihui** [comment]
In Line 432 of https://github.com/apache/singa/blob/dev-postgresql/examples/model_selection_psql/ms_mlp/train_mlp.py#L432

the gradients are returned and used in the training process

**Comment by daoducanhc** [comment]
resolved in https://github.com/apache/singa/commit/d9831d917ae0918749faacf5a611b161cbdd1fc9

**Comment by daoducanhc** [comment]
resolved in https://github.com/apache/singa/commit/d9831d917ae0918749faacf5a611b161cbdd1fc9
