### ISSUE TITLE
Update the online documentations

### ISSUE THREAD

**Issue by dcslin** [apache/singa#1210]
Update the online documentations for (1) Add the news for the SIGMOD Systems Award (2) Update the information of V 4.3.0

**Comment by lzjpaul** [comment]
Resolved in 
https://github.com/apache/singa-doc/commit/d7660ff71a00770850de9112beb3ac89a91a4b0a
and
https://github.com/apache/singa-doc/commit/2522ccb7b5fd0055eab8e177c5b8ced6852b0e54
