### ISSUE TITLE
The padding of Conv2d and Pool22 not support SAME_UPPER, SAME_LOWER

### ISSUE THREAD

**Issue by joddiy** [apache/singa#583]
Now the singa's padding is, we assign a value, and it adds the amount of value's padding at both sides of head and tail.

However, according to the [onnx doc](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv), there are four types of padding method, which are NOTSET, SAME_UPPER, SAME_LOWER or VALID. Singa cannot support SAME_UPPER, SAME_LOWER yet.

> SAME_UPPER or SAME_LOWER mean pad the input so that the output spatial size match the input. In case of an odd number add the extra padding at the end for SAME_UPPER and at the beginning for SAME_LOWER.

For example, the input is 32\*32, the stride is 1, the kernel is 4\*4, and output is same, we need to add (3,3) zeros totally, each side is 3/2 = 1.5, cannot work basing on the current setting of singa.

**Comment by nudles** [comment]
@joddiy Has the issues been fixed?

**Comment by joddiy** [comment]
yes, by PR #612
