### ISSUE TITLE
Clang-formatter results in different formatting?

### ISSUE THREAD

**Issue by chrishkchris** [apache/singa#596]
I used the clang-formatter with VS-code after I alter the tensor.h file, it results in different format with the dev branch.

![format](https://user-images.githubusercontent.com/38325429/74151458-2f68ae80-4c47-11ea-8d5b-b5107171b1b5.png)
![fromat2](https://user-images.githubusercontent.com/38325429/74153518-c59ed380-4c4b-11ea-8e6b-942fa5dedcf6.png)

The tensor.cc should have re-formatted before in PR #581. So, did I use incorrect setting in clang-formatter?

**Comment by dcslin** [comment]
Hi @chrishkchris , I have tested on windows at my side. Could you please check again your configuration? I hope this guide could help: https://github.com/apache/singa-doc/blob/0efbdbee811901fbcd7ce1f2d057669cb246e4c9/docs-site/docs/contribute-code.md

You might need to install LLVM in windows, and add below lines to VS Code configuration:
```
"[cpp]": {
    "editor.defaultFormatter": "xaver.clang-format"
},
"cpplint.cpplintPath": "path/to/cpplint",

"editor.formatOnSave": true,
"python.formatting.provider": "yapf",
"python.linting.enabled": true,
"python.linting.lintOnSave": true,
```

**Comment by chrishkchris** [comment]
I have installed LLVM, and the following VS code configuration:

{
  "git.ignoreMissingGitWarning": true,
  "python.pythonPath": "C:\\ProgramData\\Anaconda3",

  "[cpp]": {
    "editor.defaultFormatter": "xaver.clang-format"
  },
  "cpplint.cpplintPath": "c:\\ProgramData\\Anaconda3\\Scripts\\cpplint.exe",

  "editor.formatOnSave": true,
  "python.formatting.provider": "yapf",
  "python.linting.enabled": true,
  "python.linting.lintOnSave": true,
  "python.linting.pylintEnabled": true,
  "python.linting.pylamaEnabled": false,
  "C_Cpp.dimInactiveRegions": false
}


Seems to be strange. I think my setting corresponding to clang-formatter is the same as you?

**Comment by chrishkchris** [comment]
is it due to the different of cpplint we uses?
I was using pip install cpplint

**Comment by dcslin** [comment]
hi @chrishkchris have you installed this extension https://marketplace.visualstudio.com/items?itemName=xaver.clang-format

**Comment by dcslin** [comment]
> is it due to the different of cpplint we uses?
> I was using pip install cpplint

clang-format is independent from cpplint

**Comment by chrishkchris** [comment]
yes, I am using
![env](https://user-images.githubusercontent.com/38325429/74209338-4698b200-4cc2-11ea-820d-6a14e81a2202.png)

**Comment by chrishkchris** [comment]
version is the same?

**Comment by dcslin** [comment]
> version is the same?

extension is auto updated i think

**Comment by dcslin** [comment]
may be for workaround could you try to set 'clang-format.language.cpp.style' this option to google.

**Comment by chrishkchris** [comment]
> may be for workaround could you try to set 'clang-format.language.cpp.style' this option to google.

ok, I will try this one

**Comment by chrishkchris** [comment]
> may be for workaround could you try to set 'clang-format.language.cpp.style' this option to google.
> 
> ok, I will try this one

Yes, this is the solution
need to add in the json
"clang-format.language.cpp.style": "google"

Could you update this to the instruction so everyone can use the same? thanks a lot

**Comment by chrishkchris** [comment]
@shicong I will submit a PR in singa-doc to make this clear in the introduction

**Comment by chrishkchris** [comment]
@shicong I have updated the instruction in https://github.com/apache/singa-doc/pull/4. I will close this issue when everything is okay. Thanks a lot for your advice!

**Comment by chrishkchris** [comment]
In https://github.com/apache/singa-doc/pull/4, I also added also the google style for python yapf :
"python.formatting.yapfArgs" : ["--style" , "{based_on_style: google}" ]
This will be good if VSCode cannot catch the  .style.yapf and .clang-format in the project root directory, where I encountered this problem in the remote edit environment (WinSCP)

**Comment by dcslin** [comment]
Hi @chrishkchris FYI
https://github.com/apache/singa/pull/603

**Comment by nudles** [comment]
@chrishkchris  is this issue fixed?

**Comment by chrishkchris** [comment]
@nudles I think to solve is to use the same version of formatters as well as the same config for all the contributors, where I addressed in the new doc repo for the instruction of how to do the formatting https://github.com/apache/singa-doc/pull/4
Although my method may not resolve 100% of the problem (some people may use not exactly the same version, e.g. LVMM 9.0 vs 10.0), but should resolve most of the problem.

@XJDKC I remembered that Rulin has even proposed a better method than me (the same docker container with the formatter pre-installed, with the same git hooks)
