### ISSUE TITLE
Preparation for the next release

### ISSUE THREAD

**Issue by nudles** [apache/singa#622]
Release version,  2.1 vs 3.0 depending on the API change

Please tick the feature if it is done.
  - [ ] onnx (vision and nlp), model-zoo md files   @joddiy 
  - [ ] distributed training with MPI and NCCL, dist-train.md @chrishkchris 
  - [ ] computational graph with memory optimization, device.md @ Rulin 
  - [ ] new website  
  - [ ] code quality and coverage management @moazreyad 
  - [ ] dnnl integration, installation.md, build.md @dcslin 
  - [ ] tensor APIs, tensor.md @dcslin 
  - [ ] new autograd operators; upgrade existing operators, autograd.md @joddiy 
  - [ ] anything else?

Here is the checklist and [steps](http://www.apache.org/dev/release-publishing.html)
- [ ] Select a release manager. The release manager (RM) is the coordinator for the release process. It is the RM's signature (.asc) that is uploaded together with the release. The RM generates KEY (RSA 4096-bit) and uploads it to a public key server. The RM needs to get his key endorsed (signed) by other Apache user, to be connected to the web of trust. He should first ask the mentor to help signing his key. [How to generate the key](http://www.apache.org/dev/release-signing.html)?

- [ ] Check license. [FAQ](https://www.apache.org/legal/src-headers.html#faq-docs); [SINGA Issue](https://issues.apache.org/jira/projects/SINGA/issues/SINGA-447)
  - [ ] the codebase does not include third-party code which is not compatible to APL;
  - [ ] The dependencies are compatible with APL. GNU-like licenses are NOT compatible; 
  - [ ] All source files written by us MUST include the Apache license header: http://www.apache.org/legal/src-headers.html. There's a script in there which helps propagating the header to all files.
  - [ ] Update the LICENSE file. If we include any third party code in the release package which is not APL, must state it at the end of the [LICENSE](https://github.com/apache/singa/blob/master/LICENSE#L448) file and include the license boilerplate in the original file.

- [ ] Bump the version. Check code and documentation
  - [ ] The build process is error-free.
  - [ ] Unit tests are included (as much as possible)
  - [ ] Conda packages run without errors. 
  - [ ] The online documentation on the Apache website is up to date.

- [ ] Prepare the RELEASE_NOTES file. Include the following items, Introduction, Features, Bugs (link to JIRA or Github PR), Changes, Dependency list, Incompatibility issues. Follow this [example](http://commons.apache.org/proper/commons-digester/commons-digester-3.0/RELEASE-NOTES.txt). 

- [ ] Prepare DISCLAIMER file. Modify from the [template](http://incubator.apache.org/guides/branding.html#disclaimers)

- [ ] Package the release candidate. The release should be packaged into : apache-singa-VERSION.tar.gz. The release should not include any binary files including git files. Upload the release to for [stage](https://dist.apache.org/repos/dist/dev/VERSION/). The tar file, signature, KEY and SHA256 checksum file should be included. MD5 is no longer used. Policy is [here](http://www.apache.org/dev/release-distribution#sigs-and-sums)
    * apache-singa-VERSION.tar.gz
    * KEY
    * XX.acs
    * .SHA256

- [ ] Call for vote by sending an email
    ``` 
    To: dev@singa.apache.org
    Subject: [VOTE] Release apache-singa-X.Y.Z (release candidate N)

    Hi all,

    I have created a build for Apache SINGA X.Y.Z, release candidate N.
    The artifacts to be voted on are located here:  xxxx
    The hashes of the artifacts are as follows: xxx
    Release artifacts are signed with the following key: xxx
    Please vote on releasing this package. The vote is open for at least 72 hours and passes if a majority of at least three +1 votes are cast.

   [ ] +1 Release this package as Apache SINGA X.Y.Z
   [ ] 0 I don't feel strongly about it, but I'm okay with the release
   [ ] -1 Do not release this package because...

   Here is my vote:
   +1 
    ```

- [ ] Wait at least 48 hours for test responses. Any PMC, committer or contributor can test features for releasing, and feedback. Everyone should check these before vote +1. If the vote passes, then send the result email. Otherwise, repeat from the beginning.
    ```
    Subject: [RESULT] [VOTE] Release apache-singa-X.Y.Z (release candidate N)
    To: dev@singa.apache.org
 
    Thanks to everyone who has voted and given their comments. The tally is as follows.
 
    N binding +1s:
    <names>
 
    N non-binding +1s:
    <names>
 
    No 0s or -1s.
 
     I am delighted to announce that the proposal to release Apache SINGA X.Y.Zhas passed.
     ````

- [ ] Upload the package for [distribution](http://www.apache.org/dev/release-publishing.html#distribution) to https://dist.apache.org/repos/dist/release/VERSION/. 

- [ ] Update the Download page of SINGA website. The tar.gz file MUST be downloaded from mirror, using closer.cgi script; other artifacts MUST be downloaded from main Apache site. More details [here](http://www.apache.org/dev/release-download-pages.html). Some feedback we got during the previous releases:  "Download pages must only link to formal releases, so must not include links to GitHub.",  "Links to KEYS, sigs and hashes must not use dist.apache.org; instead use https://www.apache.org/dist/singa/...;", "Also you only need one KEYS link, and there should be a description of how to use KEYS + sig or hash to verify the downloads."

- [ ] Remove the RC tag and compile the conda packages.

- [ ] Publish the release information. 
    ```
    To: announce@apache.org, dev@singa.apache.org 
    Subject: [ANNOUNCE] Apache SINGA X.Y.Z released

    We are pleased to announce that SINGA X.Y.Z is released.

    SINGA is a general distributed deep learning platform for training big deep learning models over large datasets. 
    The release is available at: http://singa.apache.org/downloads.html
    The main features of this release include XXX
    We look forward to hearing your feedback, suggestions, and contributions to the project.

    On behalf of the SINGA team, {SINGA Team Member Name}
    ````

**Comment by moazreyad** [comment]
We may aim to include some internal features for developers. I wrote two discussions in the mail list, one for [Code Quality]( http://mail-archives.apache.org/mod_mbox/singa-dev/201909.mbox/%3CCAH%3DWUUbgvL62dZOCRJeEDA-a-JWNEyGvvK1Dn3ZL1YDvLXWktQ%40mail.gmail.com%3E) and the other for [Coverage](http://mail-archives.apache.org/mod_mbox/singa-dev/201911.mbox/%3CCAH%3DWUUaq4eDJKrQPyVbkCoJYQ8mjtNycXQvXUA9x4UK3MtCg%3DA%40mail.gmail.com%3E). I am planning to write more discussions for other improvements soon.

The code quality improvements seems fine now. We have lgtm, linting and license checks. But the code coverage is not ready. There are many tasks to enable coverage as proposed in the discussion. I will try to work on some of them and everyone is welcome to participate.

About 2.1 vs 3.0, I vote for 2.1.

**Comment by nudles** [comment]
Thanks for the suggestion, Moaz!
In terms of the version number, I think if we have major API changes that are not compatible with V2.0, then we need to release V3.0;

**Comment by nudles** [comment]
@moazreyad  pls help double check the release steps. This is our first release as TLP; hence it is a bit from past releases.

**Comment by moazreyad** [comment]
1. At the end, we will need to [publish the release](http://singa.apache.org/develop/how-to-release.html#publish-release).

1. The step of check license is not required. It will be done [automatically](https://github.com/apache/singa/pull/629) when any pull request is merged with master.

**Comment by dcslin** [comment]
changelog of some of the mentioned points
https://gist.github.com/dcslin/1e8934ffc791fdea4b95810f437cf361

**Comment by joddiy** [comment]
changelog of some of the mentioned points
https://gist.github.com/joddiy/ff7a5f8e8dd35668a2f300c26ad01cdb

**Comment by nudles** [comment]
@joddiy pls create the colab notebooks for the onnx examples

**Comment by joddiy** [comment]
> @joddiy pls create the colab notebooks for the onnx examples

Got it, I am going to create it right now.

**Comment by joddiy** [comment]
> @joddiy pls create the colab notebooks for the onnx examples

please check the colab examples. However, I just clean the code now, since the new version SINGA has not been released, it cannot run yet. After we release the new version, I will adjust it then.

## Face Analysis
[arcface](https://colab.research.google.com/drive/1qanaqUKGIDtifdzEzJOHjEj4kYzA9uJC), [fer+ emotion](https://colab.research.google.com/drive/1XHtBQGRhe58PDi4LGYJzYueWBeWbO23r)

## Object Detection
[tiny yolo v2](https://colab.research.google.com/drive/11V4I6cRjIJNUv5ZGsEGwqHuoQEie6b1T)

## Image Classification
[mobilenet](https://colab.research.google.com/drive/1HsixqJMIpKyEPhkbB8jy7NwNEFEAUWAf), [vgg16](https://colab.research.google.com/drive/14kxgRKtbjPCKKsDJVNi3AvTev81Gp_Ds), [resnet18](https://colab.research.google.com/drive/1u1RYefSsVbiP4I-5wiBKHjsT9L0FxLm9)

## Machine Comprehension
[bert squad](https://colab.research.google.com/drive/1kud-lUPjS_u-TkDAzihBTw0Vqr0FjCE-)

## Mnist demo for inference, re-training, and transfer learning
[mnist](https://colab.research.google.com/drive/1-YOfQqqw3HNhS8WpB8xjDQYutRdUdmCq)
