### ISSUE TITLE
AsType cannot work when after Reshape

### ISSUE THREAD

**Issue by joddiy** [apache/singa#630]
Hi, @dcslin , The asType cannot work when it is after the reshape operators.

Please check by using the following code:

```
    dev = device.create_cuda_gpu()
    X = np.array([[1, 0], [1, 1]]).astype(np.int32)
    x = tensor.from_numpy(X)
    x.to_device(dev)

    x = autograd.cast(x, tensor.int32)
    x = autograd.reshape(x, [1, 2, 2])
    x = autograd.cast(x, tensor.float32)
```

**Comment by dcslin** [comment]
hi @joddiy ,thank you for raising the issue, it should be working after this pr
https://github.com/apache/singa/blob/205a2832b23694b748134ef69ef9c0b4c642afd5/test/python/test_tensor.py#L341

**Comment by joddiy** [comment]
Thans shicong, it works fine for me.
