### ISSUE TITLE
Implement cudnn_rnn operation

### ISSUE THREAD

**Issue by nudles** [apache/singa#655]
Currently, we implement the rnn operations from scratch, which may not be as fast as the cudnn versions.
To use cudnn rnn operations, we need to implement the cpp operation and call it from the python side.
https://docs.nvidia.com/deeplearning/sdk/cudnn-api/index.html#cudnnRNNMode_t

**Comment by chrishkchris** [comment]
cudnn rnn was implemented on singa 3.1
