### ISSUE TITLE
Propose to upgrade RNN operation buffering for Graph 

### ISSUE THREAD

**Issue by chrishkchris** [apache/singa#680]
In singa/examples/rnn/train.py,

When we run it with Graph using Sequential, i.e. line 200: model.graph(True, True), the training can complete without error.

However, when we run it with Graph using node input dependencies,  i.e. line 200: model.graph(True, False), it will display the error as below:

![errorseq](https://user-images.githubusercontent.com/38325429/79296212-5eccbd80-7f0d-11ea-96f3-8e1badbb4b10.png)

Summarized from some discussion with @XJDKC, the error may be due to the following:

1. There may be some operations we have used but did not specify read_blocks and write_blocks well
2.  Hence, some operations are performed in advance because the operation is not buffer as required  

Therefore, to support computation of graph using node input dependencies, we may need to update the buffering of some RNN operation.

**Comment by chrishkchris** [comment]
addressed by PR #687

**Comment by XJDKC** [comment]
Thanks, Chris.

**Comment by chrishkchris** [comment]
solved in previous PRs
