### ISSUE TITLE
Extend the opt module

### ISSUE THREAD

**Issue by nudles** [apache/singa#692]
Refer to https://gist.github.com/nudles/d7f8043f251872333ec06f2701696cce

**Comment by chrishkchris** [comment]
There are a list of optimizers in optimizer.py but cannot use in opt.py
https://github.com/apache/singa/blob/master/python/singa/optimizer.py
I suggest we can move the optimizers from optimizer.py to opt.py
Those include:
1. class Nesterov(Optimizer):
2. class RMSProp(Optimizer):
3. class AdaGrad(Optimizer):
4. class Adam(Optimizer):
5. class L2Regularizer(Regularizer): // if regularization should be considered too

**Comment by nudles** [comment]
Following the discussion in #696 , we can have opt module and Optimizer class, loss module and Loss class. 
Each subclass of Loss is implemented using the operators in autograd module. 
Each subclass of Optimizer is implemented using functions in tensor module.

**Comment by chrishkchris** [comment]
addressed in #773

**Comment by chrishkchris** [comment]
addressed in #773
