### ISSUE TITLE
Extend the Module class

### ISSUE THREAD

**Issue by nudles** [apache/singa#693]
In  #674 , we propose to move the param creation and initialization into the forward propagation stage, i.e., `__call__`. 
However, sometimes, we may want to access the parameters of a model after it is created, e.g., 
```python
m = ModelFoo()
m.get_params()  # returns the params of each layer via get_params
```
We will get errors since the params are not created yet.
To resolve this issue, we can add a new method to the Module class
```python
def init(self, x):
    # x represents the input tensor(s) whose values could be randomly filled, 
    # but the shape and device are set correctly.
    self.forward(x)  # the forward propagation will initialize all params.
```
The following code will pass without errors.
```python
m = ModelFoo()
m.init(x)
m.get_params()  # returns the params of each layer via get_params
```

Comments are welcomed

**Comment by chrishkchris** [comment]
@XJDKC In this case, I suggest we can use the buffer operation feature so there won't be any actual run. 
Then, in case if we don't want to use graph after getting the parameter size, we can use ResetGraph to clear the buffer, then turn off buffer and run without graph.

**Comment by XJDKC** [comment]
I worry that if we move the param creation and initialization into the forward propagation stage, those initialization operations will also be buffered and included in the graph.

**Comment by chrishkchris** [comment]
> I worry that if we move the param creation and initialization into the forward propagation stage, those initialization operations will also be buffered and included in the graph.

@XJDKC Can use ResetGraph to reset the buffer?

**Comment by XJDKC** [comment]
> > I worry that if we move the param creation and initialization into the forward propagation stage, those initialization operations will also be buffered and included in the graph.
> 
> @XJDKC Can use ResetGraph to reset the buffer?

I prefer adding an initialization function for Layer

**Comment by chrishkchris** [comment]
> > > I worry that if we move the param creation and initialization into the forward propagation stage, those initialization operations will also be buffered and included in the graph.
> > 
> > 
> > @XJDKC Can use ResetGraph to reset the buffer?
> 
> I prefer adding an initialization function for Layer, the module just needs to call the init function of each layer to initialize the whole model.

Yes, in the following example to parameter of the layer is initialized in the call function, where its shape is infered from the input size of that layer 
https://github.com/apache/singa/blob/19f2020fda36032fdc26dc5910dacbfcff638e7f/python/singa/autograd.py#L3406
Can this case be handled?

**Comment by XJDKC** [comment]
> > > > I worry that if we move the param creation and initialization into the forward propagation stage, those initialization operations will also be buffered and included in the graph.
> > > 
> > > 
> > > @XJDKC Can use ResetGraph to reset the buffer?
> > 
> > 
> > I prefer adding an initialization function for Layer, the module just needs to call the init function of each layer to initialize the whole model.
> 
> @XJDKC
> Yes, in the following example the parameter of the layer is initialized in the call function, where its shape is infered from the input size of that layer
> https://github.com/apache/singa/blob/19f2020fda36032fdc26dc5910dacbfcff638e7f/python/singa/autograd.py#L3406
> 
> 
> Can this case be handled?

The handle can be created in the init function, and then W can be initialized by the handle.

**Comment by nudles** [comment]
#696
