### ISSUE TITLE
Draft for ASF board report

### ISSUE THREAD

**Issue by nudles** [apache/singa#793]
## Issues:
There are no issues requiring board attention

## Membership Data:
Apache SINGA was founded 2019-10-16 (a year ago)
There are currently 22 committers and 16 PMC members in this project.
The Committer-to-PMC ratio is roughly 3:2.

Community changes, past quarter:
- No new PMC members. Last addition was Chris Yeung on 2020-04-17.
- Zhang Zhaoqi was added as committer on 2020-07-01
- Rulin Xing was added as committer on 2020-06-23
- Shicong Lin was added as committer on 2020-06-26

## Project Activity:
The community is working on release v3.1, which include the following
features/changes:
1. generating wheel package for distributing SINGA on PyPI repo and
   simplifying the installation process.
2. moving from Travis CI to Github workflow for better integration with
   Github.
3. improving the computational graph to support RNN models
4. adding new operators to support more ONNX models
5. fixing some bugs.

## Community Health:
Overall, the community has slowed down a bit after releasing version 3.0. We
are still active in development for v3.1, with 52 PRs opened and 53 PRs
closed. The community is growing stably with 3 new committers joined since
last report.

**Comment by moazreyad** [comment]
another added feature in this release is integrating C++ and Python code coverage with codecov.io in the development workflow.

**Comment by nudles** [comment]
I will add it in the next report.
thanks!
