### ISSUE TITLE
autograd models got AttributeError

### ISSUE THREAD

**Issue by pinpom** [apache/singa#810]
Got AttributeError when running some Autograd models:

`python examples/cnn/autograd/cifar10_multiprocess.py`
AttributeError: module 'singa.singa_wrap' has no attribute 'NcclIdHolder'

`python examples/cnn/autograd/mnist_dist.py`
AttributeError: module 'singa.singa_wrap' has no attribute 'Communicator'

Does it mean that file singa_wrap is not updated?

**Comment by nudles** [comment]
this is because the pip/conda package was compiled without the distributed training module.
