### ISSUE TITLE
There are two main branches: master branch and dev branch

### ISSUE THREAD

**Issue by chrishkchris** [apache/singa#831]
There are two branches: master and dev

1. master branch consists of a stable version

2. dev branch consists of a development version

**Normally, when we do the code development, we submit PRs to dev branch. It is because it could take some risk to overwrite a stable version**

**However, sometime we still need to submit PR to master branch, for the purpose of fixing the existing bug in the master branch**

When we release a new version when the dev branch is stable, we will update the master branch from the dev branch, and use the updated master branch as the new release

**Comment by lzjpaul** [comment]
For the development works of this whole quarter, the development team has agreed and followed the following rules:

1) when we do the code development, we submit PRs to dev branch. 

2) When we release a new version when the dev branch is stable, we will update the master branch from the dev branch, and use the updated master branch as the new release
