### ISSUE TITLE
Need to disable graph for printing parameters and gradients

### ISSUE THREAD

**Issue by zlheui** [apache/singa#857]
When we are running distributed training examples, e.g., examples/cifar_distributed_cnn, examples/cnn, we need to disable graph (adding -g option), so that we can print parameter values or gradients tensors in numpy format

**Comment by lzjpaul** [comment]
Use the -g option in train_cnn.py, train_mpi.py and train_multiprocess.py solves this issue

**Comment by lzjpaul** [comment]
Use the -g option in train_cnn.py, train_mpi.py and train_multiprocess.py solves this issue
