### ISSUE TITLE
Move data augmentation outside of training iterations for better training efficiency

### ISSUE THREAD

**Issue by lzjpaul** [apache/singa#904]
In examples/largedataset_cnn/train_largedata.py, the augmentation should be moved outside of training iterations.

For benchmark datasets, e.g., CIFAR-10 and ImageNet, the augmentation method is pre-defined before the model training, so the augmentation does not need to be carried out on the fly in each iteration.

**Comment by nudles** [comment]
But, the data augmentation is done with some randomness, e.g., random cropping offset and random rotation degrees. If you move it outside of the training iterations, you may lose this randomness. As a result, you may not get much benefit from data augmentation.

**Comment by lzjpaul** [comment]
The data augmentation is remained inside each training iteration for better classification accuracy
