### ISSUE TITLE
update CMakeLists.txt

### ISSUE THREAD

**Issue by zlheui** [apache/singa#971]
the CMake compilation depends on the git tag to get the version numbers; to remove this dependency, we need to manually update the CMakeLists.txt file to set the version numbers

**Comment by lzjpaul** [comment]
the CMakeLists.txt is updated in commit: https://github.com/apache/singa/commit/fe7515f46e4526515486ab2db27fe252ee385289

**Comment by lzjpaul** [comment]
resolved
