### ISSUE TITLE
Update the version and compilation commands

### ISSUE THREAD

**Issue by KimballCai** [apache/singa#972]
Update the version and compilation commands in setup.py for v3.3 release

**Comment by KimballCai** [comment]
Update the version and compilation commands in setup.py for v3.3 release

**Comment by lzjpaul** [comment]
This has been addressed by https://github.com/apache/singa/commit/d5df6b24b14e8d2aeb0bc28eaa5bac9f0cb8e407

**Comment by lzjpaul** [comment]
addressed

**Comment by lzjpaul** [comment]
resolved

**Comment by lzjpaul** [comment]
this issues has been resolved
