### ISSUE TITLE
update conda and docker files

### ISSUE THREAD

**Issue by zlheui** [apache/singa#974]
update the conda_build_config.yaml and meta.yaml for v3.3.0

**Comment by lzjpaul** [comment]
This has been addressed in dev branch

https://github.com/apache/singa/commit/d5df6b24b14e8d2aeb0bc28eaa5bac9f0cb8e407

**Comment by lzjpaul** [comment]
This commit has been updated in the master branch in https://github.com/apache/singa/commit/d5df6b24b14e8d2aeb0bc28eaa5bac9f0cb8e407

**Comment by lzjpaul** [comment]
resolved
